module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  GET_UNITS_ERROR: "GET_UNITS_ERROR",

  // FamilyIncome
  GET_FAMILY_INCOME_ERROR: "GET_FAMILY_INCOME_ERROR",
  ADD_FAMILY_INCOME_ERROR: "ADD_FAMILY_INCOME_ERROR",
  UPDATE_FAMILY_INCOME_ERROR: "UPDATE_FAMILY_INCOME_ERROR",
  DELETE_FAMILY_INCOME_ERROR: "DELETE_FAMILY_INCOME_ERROR",

  // IncomeType
  INCOME_TYPE_NOT_FOUND: "INCOME_TYPE_NOT_FOUND",
  GET_INCOME_TYPE_ERROR: "GET_INCOME_TYPE_ERROR",
  GET_INCOME_TYPES_ERROR: "GET_INCOME_TYPES_ERROR",
  ADD_INCOME_TYPE_ERROR: "ADD_INCOME_TYPE_ERROR",
  UPDATE_INCOME_TYPE_ERROR: "UPDATE_INCOME_TYPE_ERROR",
  DELETE_INCOME_TYPE_ERROR: "DELETE_INCOME_TYPE_ERROR",
  INCOME_TYPE_IN_USE: "INCOME_TYPE_IN_USE",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  GET_USERS_ERROR: "GET_USERS_ERROR",
  GET_USER_ERROR: "GET_USER_ERROR",
  ADD_USER_ERROR: "ADD_USER_ERROR",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
  DELETE_USER_ERROR: "DELETE_USER_ERROR",
  DELETE_USER_FORBIDDEN: "DELETE_USER_FORBIDDEN",

  // Purchase
  GET_PURCHASES_ERROR: "GET_PURCHASES_ERROR",
  ADD_PURCHASES_ERROR: "ADD_PURCHASES_ERROR",
  UPDATE_PURCHASES_ERROR: "UPDATE_PURCHASES_ERROR",
  DELETE_PURCHASES_ERROR: "DELETE_PURCHASES_ERROR",

  // Item
  ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
  GET_ITEM_ERROR: "GET_ITEM_ERROR",
  GET_ITEMS_ERROR: "GET_ITEMS_ERROR",
  ADD_ITEMS_ERROR: "ADD_ITEMS_ERROR",

  // Currency
  ADD_CURRENCIES_ERROR: "ADD_CURRENCIES_ERROR",
  UPDATE_CURRENCIES_ERROR: "UPDATE_CURRENCIES_ERROR",
  DELETE_CURRENCIES_ERROR: "DELETE_CURRENCIES_ERROR",
  CURRENCY_NOT_FOUND: "CURRENCY_NOT_FOUND",
  GET_CURRENCY_ERROR: "GET_CURRENCY_ERROR",
  GET_CURRENCIES_ERROR: "GET_CURRENCIES_ERROR",

  // Items Category
  GET_CATEGORIES_ERROR: "GET_CATEGORIES_ERROR",
  EDIT_ITEMS_CATEGORY_ERROR: "EDIT_ITEMS_CATEGORY_ERROR",

  // Purchases Category Suggestion
  GET_PURCHASES_CATEGORY_SUGGESTION_ERROR:
    "GET_PURCHASES_CATEGORY_SUGGESTION_ERROR",
};
