const PERIODICITY = {
  ONE_TIME: "ONE_TIME",
  DAILY: "DAILY",
  WEEKLY: "WEEKLY",
  MONTHLY: "MONTHLY",
  YEARLY: "YEARLY",
};

module.exports = {
  PERIODICITY,
  PERIODICITY_VALUES: Object.values(PERIODICITY),
};
